### ISSUE TITLE
Opt-in to postMessage notifications when fastest updates the cached content

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-toolbox#116]
The `toolbox.fastest` strategy provides a convenient way of returning a previously cached `Response` immediately, while at the same time `fetch()`ing a potentially newer copy from the network.

However, if the network request did result in an updated copy being retrieved, the page that requested the resource does not currently receive any notification that there's a newer `Response` available.

We can add in a new option that would allow developers to opt-in to using `ServiceWorkerClient.postMessage()` to trigger an event handler on the controlled page, letting it know that the cached entry is out of date.

**Comment by gauntface** [comment]
@jeffposnick how do you see developers using this callback? Trigger a notification asking the user to perform a refresh?

Would this follow a similar pattern for when a new service worker has been installed and waiting for activation?

Any proposals for what the API could look like?

**Comment by jeffposnick** [comment]
A scenario where this would come in handy would be when revisiting a previously accessed article. Most of the time the cached copy would remain the same. On the off chance there's an important edit that was made after it was initially published, it could be useful to notify the reader (via a toast or a similar mechanism—really up to the site) that they should reload to see the latest edits. It's definitely analogous to what you can already do with App Shell updates by listening for service worker lifecycle events.

It could be something that you opt-into via our standard options object, though it would only apply to routes that use the `fastest` strategy.

Config:
```js
toolbox.router.get(/articles/, toolbox.fastest, {
  cache: {
    name: 'articles',
    maxEntries: 10
  },
  notifyOnFastestUpdate: true
});
```

Controlled page:
```js
navigator.serviceWorker.addEventListener('message', function(event) {
  // event.data.type === 'fastest-update'
  // event.data.url === 'https://example.com/articles/abc.json'
});
```

**Comment by gauntface** [comment]
Looks super nice to me, only tweak would be to the name: 'notifyOnFastestUpdate' maybe something like 'notifyOnCacheUpdate' so it's obvious that it's only triggered when the cache is actually altered (If we can make that distinction).

**Comment by wibblymat** [comment]
Definitely like the idea of adding the feature. I would make the type of the message something like `cache-updated` so that we can use this feature with other handlers we might write in the future.

We might also want to (optionally) do some check to make sure that we only notify if the version from the network is actually different from the version in the cache.

For the purpose of playing devil's advocate, and for provoking discussion, I'm going to describe two alternative APIs

**The simplest thing that could possibly work**.
No options or configuration. Every time `fastest` updates the cache we postMessage all controlled window clients to let them know. It has the advantage of simplicity.

It also solves an admittedly very low priority problem when you have more than one open window client. Say that client A fetches a resource with fastest while offline. The resource comes from the cache and the network request fails, so there is no update ping. Later, client B fetches the resource while online. When the network fetch succeeds, BOTH clients will be notified.

For disadvantages, I'm not sure. It would depend on how heavyweight the process is. If you're not checking that the resource really changed then I think it's probably negligible, in which case why not?

**Decouple from routing**
Instead of having it as part of the route, have an API to subscribe to notifications when certain resources change in the cache. This would also work across all clients. I don't really think this approach adds anything, but I wanted to throw it out as a thought :)

In the same scenario as above, you could also notify when the cacheFirst and networkFirst handlers update the cache. Again, this only has a benefit for multiple client situations. Client A loads something with cacheFirst with an empty cache, or networkFirst, while offline and gets either no data or stale data. Later, client B loads the same resource and gets a network response. Client A can then be notified and get the fresh data.

**Comment by jeffposnick** [comment]
FYI, I'm going to work on this soon, as the need has come up again.

Based on the previous comments, I'm thinking that `notifyOnCacheUpdate` for the name, and you have to explicitly opt-in.

The one wrinkle is that for the specific use case I'm focusing on, the message should only be sent iff the previously cached entry and the new entry from the network are actually different (with some degree of certainty). Comparing response bodies is way too heavyweight, so I'm hoping I can get away with comparing Content-Length, falling back to Last-Modified (if present) and then ETag (if present).
