### ISSUE TITLE
Set up test automation

### ISSUE THREAD

**Issue by wibblymat** [GoogleChrome/sw-toolbox#15]
Probably involving Selenium and Travis.

Depends on #5

**Comment by jeffposnick** [comment]
Additionally, `gulp test` should run the existing tests, not just run the `jshint`-based linting like it currently does.

**Comment by jeffposnick** [comment]
Travis CI supports SauceLabs, but I believe that requires a paid subscription.

Travis CI also supports [headless Firefox via `xvfb`](http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)), so that might be a viable solution once service worker support lands in the Firefox stable builds.

**Comment by jeffposnick** [comment]
@samccone has a writeup of the setup he's used at http://samsaccone.com/posts/testing-with-travis-and-sauce-labs.html

**Comment by gauntface** [comment]
I made a single test with `gulp test` here.

https://github.com/GoogleChrome/sw-toolbox/tree/wider-test-coverage

Uses mocha and a chai.should.

I'll have a look at getting this automated with travis - would like to avoid using sauce labs if possible, but will look at how the platinum elements do it and report back tomorrow.

**Comment by samccone** [comment]
yeah, sauce is not 100% needed if you only want to test in chrome,

for instance on todomvc we only test in chrome on travis.ci
you can lift our setup here if you want

https://github.com/tastejs/todomvc/blob/master/.travis.yml#L31-L32

:wave: :smile:

**Comment by gauntface** [comment]
Awesome, thanks @samccone.

**Comment by jeffposnick** [comment]
It would be _nice_ to not tie ourselves to Chrome in this tests, in case we end up hitting some obscure bug in Firefox's soon-to-be-shipping service worker implementation.

But automated Chrome-only testing is strictly better than no automation. We could always run Firefox tests manually.

**Comment by samccone** [comment]
we **can** use firefox on travis (: that is the easy one :) :dog: 

https://docs.travis-ci.com/user/firefox/

:art: :truck:

**Comment by gauntface** [comment]
cc @samccone @wibblymat @jeffposnick 

First crack - firefox and chrome test running.

Branch: https://github.com/GoogleChrome/sw-toolbox/tree/wider-test-coverage
Travis: https://travis-ci.org/GoogleChrome/sw-toolbox/builds/100611454

Approach is as follows:

`gulp test:automation` will start a server and run mocha test suite - test/automation-suite.js. This will open a browser, navigate to the in browser mocha tests (test/index.html), wait for `window.swtoolbox.testResults` to become defined, get the value of testResults and then use that to pass or fail the test (printing the test titles via an error if any failed).

Inside test/index.html - The tests will not be run if service worker isn't supported - this means we can set travis up to run in browser and as service worker becomes supported the tests will kick in as appropriate (if we want to). The swtoolbox variable is generated by listening to `pass` and `fail` events from the `mocha.run()` call.

The reason for the mocha running inside the browser rather than move them all out to seperate tests to be run via selenium is that:

1. In browser mocha will lead to faster manual testing (just navigate to the url and you are good - no selenium starting and stopping browsers), plus it's easier to view console logs.
2. The code for instantiating, managing and removing service workers and caches is easier directly in the browser rather than through selenium.

Major thing I need to explore is this approach is ok with everyone - is how to test in the various browser versions (beta, nightly) etc

What are peoples initial thoughts on this approach?

**Comment by jeffposnick** [comment]
@gauntface, is your plan to recreate all the QUnit tests? Or will the existing QUnit tests need to be run in conjunction with the new tests?

I'm not as familiar as you are with the tradeoffs between "Mocha in browser" vs. "separate tests via Selenium". I can say that I think the cleanest model for service worker/cache testing is to start each test run from a known state—ideally, via a new user profile in a fresh browser instance. I believe that's what you get by default when you let Selenium launch your browsers for you, and it's seemed to work for the `wct`-driven tests in, e.g., [`<platinum-sw>`](https://github.com/PolymerElements/platinum-sw).

I'm concerned that [attempts](https://github.com/GoogleChrome/sw-toolbox/blob/wider-test-coverage/test/libs/helper-functions.js) to reset the service worker/cache state via JavaScript to make the tests re-runnable in the same browser instance could end up in flakiness and/or artifacts that aren't representative of how the code would behave "in the wild".

(When I was manually running the QUnit tests, I launched them each time in a new Incognito Chrome window.)

**Comment by jeffposnick** [comment]
Or maybe I'm misunderstanding your distinction here? Because I just tried running `npm test` using a local copy of your branch, and it appeared to automatically start fresh copies of both Chrome and Firefox. So why are the utility functions to clean up previous service worker installations/caches needed?

**Comment by gauntface** [comment]
I intend to replicate the qunit tests in mocha.

The way you can get reliable state is to use a timestamp for the service worker scope and a test page url that fits inside this scope.

The nice thing with this is that if a service worker doesn't unregister before the next test, it doesn't matter because the scope means it won't affect the following test.

The helper functions are there to help with this timestamp / iframe management and remove a lot of repetitive code.

The end goal would be to have more than the one test that is currently run in the inbrowser tests (run gulp test:manual and go to localhost:8888).

**Comment by wibblymat** [comment]
Generally seems fine to me. Being able to run all tests in a single page is a great quick check during development

**Comment by gauntface** [comment]
@jeffposnick @wibblymat Update:

I've added some tests for `.precache` and `router.get` (some based off of the origin qunit tests).

`router.get` methods show how we can test requests that go through the service worker: https://github.com/GoogleChrome/sw-toolbox/blob/wider-test-coverage/test/inbrowser-tests/router-get.js

The way it works is that each test creates an `iframe`. That iframe's `src` is set to `/test/iframe/<timestamp>`. This forces it to have a unique URL between tests. The test then activates a service worker via `testHelper.activateSW`. Behind the scenes this looks for the `iframe` (given a known html class name) and if it finds one, activates the service worker with a `scope` of the iframes `src` (See: https://github.com/GoogleChrome/sw-toolbox/blob/wider-test-coverage/test/inbrowser-tests/libs/helper-functions.js#L110). After this you can use the iframe to make a request by using the iframes fetch request (this relies on the service worker the claim call in the activate step).

`iframe.contentWindow.fetch(fetchUrl)`

I had to create an express server to add in the `Service-Worker-Allowed` header: https://github.com/GoogleChrome/sw-toolbox/blob/wider-test-coverage/test/server/index.js#L28 and return a page for the `/test/iframe/<timestamp>` page.

At the moment creating the tests isn't too bad, but I need to play with the folder structure a little more - at the moment it feels messy. If the tests fail, debugging isn't clean. If there was a way to set up a specific test and no others without the tear down after the test would do a long way to help fixing issues, but not sure what that would look like at the moment.

I've left some tests failing because I think the behaviour is worth discussing before it all goes through as passing. I may make these ignorable tests.

Feedback on this would be good now that it's performing a few more tests.

To run them from gulp you can use `gulp test:manual` or `gulp:automated`. Otherwise `nodemon test/server/index.js` will also do the job.

**Comment by gauntface** [comment]
@wibblymat @jeffposnick 

Initial move of the tests over to mocha + selenium is done.

I've got a number of tests are speed  due to the test is either passing when it results in odd behavior or the test itself would likely be flakey - better instrumentation or a different approach to testing behavior is needed.

Main thing I want to explore is testing on different versions of firefox and chrome - if possible.

**Comment by jeffposnick** [comment]
Doing some housekeeping—I think this one is safe to close thanks to @gauntface's work.

**Comment by gauntface** [comment]
+1 on closing
