### ISSUE TITLE
Google Analytics + platinum-sw causing error

### ISSUE THREAD

**Issue by jonmann20** [GoogleChrome/sw-toolbox#153]
```html
<!-- index.html -->
<script async src="https://www.google-analytics.com/analytics.js"></script>

<platinum-sw-register auto-register base-uri="platinum-sw/bootstrap">
	<platinum-sw-cache default-cache-strategy="fastest"></platinum-sw-cache>
</platinum-sw-register>
```

```js
// console
sw-toolbox.js:18 Uncaught (in promise) TypeError: Request scheme 'data' is unsupported(…)(anonymous function) @ sw-toolbox.js:18
```

**Comment by jeffposnick** [comment]
Thanks for reporting this.

It turns out that under some scenarios, HTTP requests for `https://www.google-analytics.com/analytics.js` result in a HTTP 307 Redirect, with a `data:` URI containing Base 64-encoded JavaScript in the `Location:` header.

A service worker isn't happy about handling a `fetch` event that redirects to a `data:` URI. It's not specific to `<platinum-sw>` or `sw-toolbox`, _per se_.

I'm following up with some Google Analytics folks to figure out what conditions trigger the HTTP 307 redirect, and will loop in the Chrome service worker engineering team to see whether they consider the currently implemented behavior a bug or not, along with any patterns that they recommend in the JavaScript that implements the service worker.

**Comment by jeffposnick** [comment]
After speaking to the Google Analytics engineering team, I have some confirmation that the HTTP 307 redirect isn't something that they're responsible for.

Instead, it sounds like the most likely culprit is a Chrome extension. This [Stack Overflow thread](http://stackoverflow.com/questions/27945501/307-redirect-when-loading-analytics-js-in-chrome) is relevant, and includes some information as to how you could track down which extension is responsible.

I'm going to close this for now because I don't think there's anything actionable on our end, but I'm curious to hear what Chrome extension caused this. And if it turns out that it wasn't a Chrome extension and there's some other root cause, feel free to reopen.

**Comment by georapbox** [comment]
In my case, the reason for the 307 redirect was uBlock Origin extension. Tested on Chrome and Vivaldi browsers. On Firefox uBlock jiust blocks `https://www.google-analytics.com/analytics.js` without causing any redirection. As @jeffposnick mentioned it's not specific to `sw-toolbox` as I don't use it at all and my service worker also complains.
