### ISSUE TITLE
Question: when does request need to be cloned?

### ISSUE THREAD

**Issue by samertm** [GoogleChrome/sw-toolbox#162]
Looking at strategies/fastest.js, when does request need to be cloned?

>     helpers.fetchAndCache(request.clone(), options)
>       .then(maybeResolve, maybeReject);
> 
>     cacheOnly(request, values, options)
>       .then(maybeResolve, maybeReject);

https://github.com/GoogleChrome/sw-toolbox/blob/master/lib/strategies/fastest.js#L45

Why is request cloned before it's passed to fetchAndCache? And if it needs to be cloned for fetchAndCache, why doesn't it need to be cloned for cacheOnly?

**Comment by wibblymat** [comment]
The body of a request is a stream that can only be read once. Fetching a request reads the body, as does writing the request to a cache. You'll see that `fetchAndCache` does another `.clone()` when passing the request to `fetch`.

If I did `fetch(request).then(response => cache.put(request, response));` then the `cache.put` would fail because the body is no longer readable.

`cacheOnly` doesn't ever read the body of the request, IIRC, as it matches the cache based on headers and URL instead.

It's *possible* that the first `clone()` isn't necessary, because the `cacheOnly` call should still work even if the body was read. I suspect that I originally wrote `fetchAndCache` without doing it's own clone and so had to clone when calling it. Then later added it in when one of the *other* strategies didn't work properly.

**Comment by wibblymat** [comment]
Hopefully that answers the question, feel free to reopen if not.
