### ISSUE TITLE
maxAgeSeconds and `fastest`

### ISSUE THREAD

**Issue by ktmud** [GoogleChrome/sw-toolbox#164]
When used with `fastest` strategy, the `maxAgeSeconds` option somehow becomes peripheral. Because the cache always expires after a response is returned.

When users refresh a page served by `fastest`, existing cache always kicks in first, even that it might already expired.

``` javascript
toolbox.cacheFirst('/mypage', {
    cache: {
        name: 'mypage',
        maxAgeSeconds: 10
    }
});
```

**Comment by jeffposnick** [comment]
Yeah, I can see how that would be confusing. The rationale behind it is that we want to take cache expiration out of the critical path of returning a `Response` to the page, so as to minimize the perceived overhead. Performing the cleanup logic, which relies on IndexedDB, prior to returning `Response` would be needed to get the behavior you expect.

I think it's more likely that we will just make that clearer in the documentation rather than introduce the potential overhead. That being said, the current implementation is going to be abstracted away into a [standalone library](https://github.com/GoogleChrome/sw-helpers/issues/33), so I'm going to figure out that bit first and see if it leads to any follow-on implementation changes.

**Comment by adityapunjani** [comment]
@jeffposnick I agree we shouldn't block returning a response, but I think we can still schedule an async (promise) cache clean up in both `cacheFirst` and `cacheOnly` strategies, before returning the response. It will guarantee out of date caches being purged eventually. This along with a sync cache expiration on SW startup might address most of the concerns. However, even this is still a _stale-while-revalidate_ kind of implementation.

**Comment by jeffposnick** [comment]
@adityapunjani, thanks for providing more context when we spoke recently.

One alternative that I was thinking about, which I believe is different than your approach, would be to subtract `maxAgeSeconds` from `Date.now()`, compare that to the `Date` header in the cached response, and not use the cached response if it's stale based on that criteria. That manages to avoid blocking on an IndexedDB lookup. If there isn't a `Date` header available for whatever reason, we could fall back to the previous behavior.

@adityapunjani, would that satisfy your use case?

Whatever we decide here should also carry over to the standalone version of the logic in [`sw-helpers`](https://github.com/GoogleChrome/sw-helpers).

**Comment by adityapunjani** [comment]
@jeffposnick Sorry just saw this. 

That seems like a good solution. Definitely covers our use cases. Would this mean changing the existing behaviour of `maxAgeSeconds ` option?

**Comment by adityapunjani** [comment]
cc @wibblymat

**Comment by jeffposnick** [comment]
Can the interested parties (@adityapunjani, @ktmud) locally try out the new code in https://github.com/GoogleChrome/sw-toolbox/tree/maxAge-fresh-response-check and see if it accomplishes what you expect?
