### ISSUE TITLE
decode URI params

### ISSUE THREAD

**Issue by jimmywarting** [GoogleChrome/sw-toolbox#212]
I had something with space included
```
/api/books/:book/:page
```
Was going to make a query agains the book but got no match since `value.book` include %20 (space) so i had to decodeURI. Something i think can be done automatically by sw-toolbox

**Comment by jeffposnick** [comment]
Could you provide more insight as to what the actual, live URL paths look like on your site and the specific routing configuration you're using with `sw-toolbox`?

I have a feeling that the `RegExp`-based routing should be able to handle this without much of an issue, but I'm not surprised if the Express-style routing has trouble.

**Comment by jimmywarting** [comment]
```js
router.get('/tv/:channel', ({channel}){
  console.log(channel) // ABC%20news
  channel = decodeURI(channel)
})
```

and the url:
localhost:8080/tv/ABC news/

**Comment by jeffposnick** [comment]
Thanks, now I understand what you mean.

At this point, I don't feel comfortable changing the way `sw-toolbox` passes named parameters to the route callback, given the potential for surprising folks who were relying on the old behavior, and because this is the first time it's been requested by a developer.

Explicitly handling URL decoding within your own code (or explicitly URL encoding strings that you're going to match against the named parameters), if you work with URLs that contain characters which require it, is the best approach given the situation.
