### ISSUE TITLE
map url and still use cacheFirst

### ISSUE THREAD

**Issue by jimmywarting** [GoogleChrome/sw-toolbox#216]
I want more better looking urls so I want to show them `/login.html` but I want the url to be just `/login` I can't do this if i want to use `toolbox.cacheFirst` do you have any solution for this?

**Comment by jeffposnick** [comment]
It's outside of the scope of `sw-toolbox` to perform URL rewriting. You also don't want that to be performed inside of a service worker in general, since the service worker won't be installed the first time a user visits your site, and not all browsers support service workers.

If you need URL rewriting, that should be done on the server to ensure that your URLs are consistent and behave properly independent of any service worker.
