### ISSUE TITLE
Service worker failed to Install in production

### ISSUE THREAD

**Issue by mbj36** [GoogleChrome/sw-toolbox#263]
Hello @jeffposnick 

My website is hosted from gh-pages which is at https://mbj36.github.io/community-app/?baseApiUrl=https://demo.openmf.org#/ but i am unable to install service workers in production. Locally everything works fine 

gh-pages branch link - https://github.com/mbj36/community-app/tree/gh-pages

I am using grunt-gh-pages to deploy. I am using this branch https://github.com/mbj36/community-app/tree/offline-reskin to deploy to gh-pages

**Comment by jeffposnick** [comment]
Here's what I see in the Application panel of Chrome DevTools, under the Errors for your service worker, when I visit https://mbj36.github.io/community-app/?baseApiUrl=https://demo.openmf.org#/

![screen shot 2017-07-27 at 5 12 36 pm](https://user-images.githubusercontent.com/1749548/28692536-fb35a0e8-72ee-11e7-829c-fd5214676f90.png)

This failure is due to the fact that the service worker needs to precache all of its dependencies in order to consider the installation successful, and the request for the (relative URL) `https://mbj36.github.io/community-app/scripts/almond/almond.js` dependency resulted in a 404 response. You should check to see why that expected `almond.js` file isn't being deployed.

**Comment by mbj36** [comment]
Hey @jeffposnick I managed to register service worker in production and everything is working fine. When i open the url (https://mbj36.github.io/community-app/?baseApiUrl=https://demo.openmf.org#/) on my mobile device it also asks me to add to home screen which is also cool but when i generate lighthouse report , one of the audits says `User will not be prompted to install the web app` but i have cached my start_url. What could be the workaround ?

I am also not able to visit https://mbj36.github.io/community-app/ offline 

![selection_052](https://user-images.githubusercontent.com/9936881/28724751-c5f1d736-73d8-11e7-8b74-2a12c38e6afb.png)

**Comment by jeffposnick** [comment]
Only the version of the root URL with `index.html` is being cached. It sounds like you should also be caching the version of the root URL without it. This might be because you're telling `sw-toolbox` to cache `'/'` when you really should be telling it to cache `'./'`.

**Comment by mbj36** [comment]
Hi @jeffposnick Why i am getting the error on Manifest Error `Manifest: one of 'url' or 'id' is required, related application ignored.` even my manifest contains start_url 

Link to Manifest - https://github.com/mbj36/community-app/blob/gh-pages/manifest.json

**Comment by jeffposnick** [comment]
I'm sorry, but we're outside of the realm of questions that related to `sw-toolbox`.

**Comment by mbj36** [comment]
Thanks for the support :)
