### ISSUE TITLE
sw-toolbox Mock Interest?

### ISSUE THREAD

**Issue by localnerve** [GoogleChrome/sw-toolbox#82]
I've created a [mock](https://github.com/localnerve/flux-react-example-sw/blob/master/tests/mocks/sw-toolbox.js) for sw-toolbox to unit test my code that uses sw-toolbox.

I'm happy to donate it (or some form of it) here if this project thinks this is a good thing to do/allow.

Regardless, would be good to get technical feedback on this.

[Example usage](https://github.com/localnerve/flux-react-example-sw/blob/12ce61b188a7bf9a61ef63823a6e276ad92b3437/tests/unit/sw/assets.js)

[Better example usage](https://github.com/localnerve/flux-react-example-sw/blob/cc7bef168e5e4528ad994536f71937e3740d85e8/tests/unit/sw/init/backgrounds.js)

Thanks again for creating this library.

**Comment by gauntface** [comment]
I've spent quite a bit of time testing sw-toolbox in Chrome and Firefox and it's been super useful from the stand point that it's revealed some differences between the two (and possibly will reveal more differences as browsers support SW) so I think it's serving our needs for now.

Generally though the work you've done looks great.

I'm going to close this bug since it hasn't had any movement for some time.
