### ISSUE TITLE
Add ability to clear a cache

### ISSUE THREAD

**Issue by owencm** [GoogleChrome/sw-toolbox#93]
Imagine a case where I have all my resources internationalized such that when the user changes their language I want to clear the caches and re-cache the new versions in the other language.

Is there any way to clear a specific cache to support this case? Or should I be creating new ones with new versions somehow? (perhaps modify toolbox.options.cache.name?)

**Comment by jeffposnick** [comment]
Deleting caches is arguably best done via [`caches.delete(cacheName)`](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/delete) directly. I'm not sure what `sw-toolbox` would offer beyond what you'd get by calling the underly Cache Storage API directly.

Setting `toolbox.options.cache.name` would be a good idea, yes, so that you can delete that named cache when needed.

I'm closing for now, but if there's a specific use case you fell isn't covered by `caches.delete()`, feel free to re-open with more details.

**Comment by owencm** [comment]
Thanks for getting back to fast!

I'm looking at a demo site from a partner and they seem to also have entries in IndexedDB corresponding to those caches. Is there cleanup work that needs to happen in IDB too, or is it fine just to clear the cache?

**Comment by rejhgadellaa** [comment]
Bump. Clearing the cache alone doesn't clear the entries in indexedDB
