### ISSUE TITLE
Dynamic paths

### ISSUE THREAD

**Issue by mbrevda** [GoogleChrome/sw-toolbox#94]
How can I specify a dynamic path, like `location.origin`?

**Comment by gauntface** [comment]
Can you be a bit more specific with what you are trying to do?

Service workers have access to `location.origin` and I think it's used in a few places in the tests..

**Comment by mbrevda** [comment]
The issue is that the variable is being evaluated in the context of the sw-cache build script, when it's being built. Would need some way of having it evaluated in the context of the sw, during actual run time.

**Comment by gauntface** [comment]
Sorry, still not with you so please bare with me.

When you say 'sw-cache build script' are you referring to sw-precache?

Any chance of example code?

cc @jeffposnick in case this makes more sense to you.

**Comment by jeffposnick** [comment]
As @gauntface says, a concrete example of the code or build configuration you're using would go a long way towards clearing up your question.

**Comment by mbrevda** [comment]
Sorry for being so obtuse. Ill elaborate with more code. (yes, I'm talking
about sw-precache)

**Comment by mbrevda** [comment]
Here is what I was trying to do:
```
        runtimeCaching: [
                {
                    urlPattern: new RegExp('^' + location.origin + '/.*'),
                    handler: 'cacheFirst'
                },
```
And I'm getting an error (`ReferenceError: location is not defined`) - which is understandable, as location is not set. The question is how would you specify something that wont be evaluated until later?

Perhaps allowing urlPattern to be a function might work?

**Comment by gauntface** [comment]
I think this would be better raised on sw-precache's issue list: https://github.com/GoogleChrome/sw-precache/issues

sw-toolbox is used by sw-precache in the final service worker produce, but this problem is specific to sw-precaches output to a service worker, or at least I think it is..

**Comment by jeffposnick** [comment]
So this is sort of a `sw-toolbox` issue, because there are two ways of specifying a route for `sw-toolbox`: using a string or a `RegExp`. Whatever you specify in `urlPattern` in `sw-precache` will get passed along directly to `sw-toolbox` when defining the route.

If you'd like to make sure that your oute only matches URLs on the current origin, that's the default behavior you get when using a string, so the following would work:

runtimeCaching: [{
  urlPattern: '/(.*)',
  handler: 'cacheFirst'
}]

(Though using `sw-toolbox`'s `cacheFirst` handler for every local URL seems like a bad idea to me, since, for one thing, that's something that `sw-precache` could handle for you in a safer, versioned fashion. Runtime caching is more appropriate for remote resources or local dynamic resources.)

There are more details about the two ways of defining routes in the [`sw-toolbox` docs](https://github.com/GoogleChrome/sw-toolbox#basic-routes).

**Comment by gauntface** [comment]
Im missing something.

The original issue suggested that precache doesn't allow a way to define a url pattern that would be possible in the context of a sw.

I.e. precache evaluates the regex in the context of the build process which doesn't have location and hence can't pass it along to sw-toolbox.

**Comment by jeffposnick** [comment]
The behavior that @mbrevda is looking for is to use a path wildcard that will only match on requests made to the local origin. That is the same behavior you'd get if you use ["Express-style" route configuration](https://github.com/GoogleChrome/sw-toolbox#express-style-routes) (without specifying the additional `{origin: ...}` option).

So I'm suggesting that there's no need to try to get `location.origin` evaluated at build time, since passing in a string for `urlpattern` gets interpreted as an Express-style route, and you'll implicitly get the desired behavior.

(I'm also suggesting that trying to apply `sw-toolbox`'s `cacheFirst` handler to every local URL is a mistake, and that `sw-precache` can just take care of those requests out of the box in safe fashion.)

**Comment by gauntface** [comment]
Could there be a scenario where the page origin is different to the sw
origin?

**Comment by jeffposnick** [comment]
No, a service worker hosted on `www.foo.com` can't control a page on `www.bar.com` due to the scope restrictions in place.

**Comment by gauntface** [comment]
Totally right, was wondering if the scope header could do something funky but realising that doesn't change origins.

**Comment by mbrevda** [comment]
So the answer to what I want is [simple](https://github.com/GoogleChrome/sw-toolbox/issues/94#issuecomment-189317772). Although that doesn't actually answer what I asked, but I'm fine with that for now.

> (Though using sw-toolbox's cacheFirst handler for every local URL seems like a bad idea to me, since, for one thing, that's something that sw-precache could handle for you in a safer, versioned fashion. Runtime caching is more appropriate for remote resources or local dynamic resources.)

To be honest, I found sw-precache's documentation and arguments to be extremely confusing. On top of that, I'm using a front end host that puts *some* assets on a cdn. I'm utterly confused about how to cache my spa's index.html (which is never server under that name), and how to specify which assets to pull from the cdn and which to pull from the same domain as `local.origin`. So while it might be a bad idea, until it bites me (and I'm assuming it will at some point), it's the simplest :confused:.

**Comment by jeffposnick** [comment]
I apologize for the documentation confusion—some options in particular in `sw-precache`, like [`navigateFallback`](https://github.com/GoogleChrome/sw-precache#navigatefallback-string), grew organically as the need arose, and aren't explained as clearly as they could be.

I'm CC:ing @jpmedley, as he's been involved in the effort to reconcile the docs for `sw-precache` and `sw-toolbox` and tell a coherent story for common development scenarios.

Here are a few disparate resources that might help in the meantime:

- In [this issue](https://github.com/GoogleChrome/sw-toolbox/issues/85#issuecomment-189352991), I outline some reasons that using `sw-precache` along with `navigateFallback` will give you an more robust caching setup—one in which existing clients get updated versions of your code, which won't happen if you just use `sw-toolbox`'s `cacheFirst` for everything.
- The [`app-shell-demo`](https://github.com/GoogleChrome/sw-precache/tree/master/app-shell-demo) shows how to configure `sw-precache` for your App Shell and `sw-toolbox` for your dynamic content in a SPA-setup. It's React-based, and there's a [related video](https://www.youtube.com/watch?v=jCKZDTtUA2A) and [article](https://developers.google.com/web/updates/2015/11/app-shell?hl=en).
- There's a newer "[Getting Started](https://github.com/GoogleChrome/sw-precache/blob/master/GettingStarted.md)" guide in the `sw-precache` project.

Regarding the CDN, if you're referencing remote assets that include version information as part of their URL (e.g. `https://cdn.com/libs/my-lib-1.0.0.js`) then it's safe to use a `cacheFirst` strategy for those, since they will never be updated without getting a new version and a new URL.

Thanks for your feedback, and I think that this helps me, @jpmedley, and the rest of the team think about the current deficiencies in how we're presenting information to developers.
