### ISSUE TITLE
Should Default Route include all methods?

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-toolbox#95]
As a last resort developers can define a default route:

> sw-toolbox supports defining an optional "default" route via toolbox.router.default that is used whenever there is no alternative route for a given URL. If toolbox.router.default is not set, then sw-toolbox will just ignore requests for URLs that don't match any alternative routes, and the requests will potentially be handled by the browser as if there were no service worker involvement.

    // Provide a default handler for GET requests
    toolbox.router.default = myDefaultRequestHandler;

At the moment it's restricted to just GET requests which isn't mentioned in the above description, but is in the code snippet. I can see the reasoning why reducing to GET requests would make sense, reduced the number of scenarios people have to consider and expect only page assets to go through this route, but it does block any manipulation of API requests made as a POST request.

Checking the request type and falling back to the network seems like an easy enough scenario if get requests are the only thing to be worried about so would opening this up to all requests make sense?

Thoughts @addyosmani @wibblymat @jeffposnick @PaulKinlan @paullewis

**Comment by jeffposnick** [comment]
I think the general idea is (almost) no site would want one-size-fits-all caching policy that would apply equally to `GET`s and to requests that mutates state.

Also, the Cache Storage API will throw a `TypeError` if you attempt to use a non-`GET` `Request` object as a cache key, and the strategies most likely to be used as `default` behaviors entail using the Cache Storage API.

It's much more likely that a site would want to apply a global policy to `GET`s, so we use `default` for that, and then folks can define one-off policies for specific combinations of HTTP verbs and paths, independent of `default`.

I'm not sure what you mean by "does block any manipulation of API requests made as a POST request", since the following should work:

```js
toolbox.router.post(/api^/, myCustomPostHandler);
toolbox.router.put(/api^/, myCustomPutHandler);
toolbox.router.default = myDefaultRequestHandler;
```

The routing to handlers should match in the order they're registered, and it will only fall through to `default` if there's no other match and it's a `GET`. If there's no other match and it's not a `GET`, then the network (or a `fetch` handler registered elsewhere) will always be used.

**Comment by wibblymat** [comment]
To add to what Jeff said, `default` did actually apply to all methods when
we started, but of the built-in handlers only `networkOnly` (which is kind
of useless) would work. So we changed the behaviour.

If you want a default POST handler, though, you can do
`toolbox.router.post(/./, myDefaultPostHandler)` and just make sure it's
the last POST handler that gets registered.

**Comment by gauntface** [comment]
Fair enough.

The only comment is in the example Jeff gives just reads as default will still catch anything remaining. But can appreciate that it may be more confusing than it's worth.
